{
 "title": "ACM - Clusters Overview - OCP 3.11",
 "tags": [ "ACM" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Control Plane Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Server",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(apiserver_request_duration_seconds:histogram_quantile_99{clusterType=\"ocp3\"}) by (cluster)"
    },
    {
     "expr": "(sum(up{clusterType=\"ocp3\",job=\"apiserver\"} == 1) by (cluster) / count(up{clusterType=\"ocp3\",job=\"apiserver\"}) by (cluster))"
    },
    {
     "expr": "sum by (cluster)(sum:apiserver_request_total:1h{clusterType=\"ocp3\",code=~\"5..\"})"
    }
   ]
  },
  { "title": "Optimization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU",
   "type": "table",
   "description": "Highlights % differences between CPU requests commitments vs utilization.  When this difference is large ( >20%), it means that resources are reserved but unused.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(sum(cluster:kube_pod_container_resource_requests:cpu:sum{clusterType=\"ocp3\"}) by (cluster) / sum(kube_node_status_allocatable_cpu_cores{clusterType=\"ocp3\"}) by (cluster)) - (1 - avg(rate(node_cpu_seconds_total{clusterType=\"ocp3\",mode=\"idle\"}[$__rate_interval])) by (cluster))"
    },
    {
     "expr": "sum(cluster:kube_pod_container_resource_requests:cpu:sum{clusterType=\"ocp3\"}) by (cluster) / sum(kube_node_status_allocatable_cpu_cores{clusterType=\"ocp3\"}) by (cluster)"
    },
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{clusterType=\"ocp3\",mode=\"idle\"}[$__rate_interval])) by (cluster)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "table",
   "description": "Highlights % differences between Memory requests commitments vs utilization.  When this difference is large ( >20%), it means that resources are reserved but unused.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "(sum(cluster:kube_pod_container_resource_requests:memory:sum{clusterType=\"ocp3\"}) by (cluster) / sum(kube_node_status_allocatable_memory_bytes{clusterType=\"ocp3\"}) by (cluster)) - (1 - sum(:node_memory_MemAvailable_bytes:sum{clusterType=\"ocp3\"}) by (cluster) / sum(kube_node_status_allocatable_memory_bytes{clusterType=\"ocp3\"}) by (cluster))"
    },
    {
     "expr": "sum(cluster:kube_pod_container_resource_requests:memory:sum{clusterType=\"ocp3\"}) by (cluster) / sum(kube_node_status_allocatable_memory_bytes{clusterType=\"ocp3\"}) by (cluster)"
    },
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum{clusterType=\"ocp3\"}) by (cluster) / sum(kube_node_status_allocatable_memory_bytes{clusterType=\"ocp3\"}) by (cluster)"
    }
   ]
  },
  { "title": "Capacity / Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{clusterType=\"ocp3\"}) by (cluster)"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores{clusterType=\"ocp3\"}) by (cluster)"
    },
    {
     "expr": "sum(cluster:kube_pod_container_resource_requests:cpu:sum{clusterType=\"ocp3\"}) by (cluster) / sum(kube_node_status_allocatable_cpu_cores{clusterType=\"ocp3\"}) by (cluster)"
    },
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{clusterType=\"ocp3\",mode=\"idle\"}[$__rate_interval])) by (cluster)"
    }
   ]
  },
  {
   "title": "Top 5 Utilized Clusters (% CPU usage)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(5, (1 - avg(rate(node_cpu_seconds_total{clusterType=\"ocp3\",mode=\"idle\"}[$__rate_interval])) by (cluster)))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(machine_memory_bytes{clusterType=\"ocp3\"}) by (cluster)"
    },
    {
     "expr": "sum(cluster:kube_pod_container_resource_requests:memory:sum{clusterType=\"ocp3\"}) by (cluster) / sum(kube_node_status_allocatable_memory_bytes{clusterType=\"ocp3\"}) by (cluster)"
    },
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum{clusterType=\"ocp3\"}) by (cluster) / sum(kube_node_status_allocatable_memory_bytes{clusterType=\"ocp3\"}) by (cluster)"
    }
   ]
  },
  {
   "title": "Top 5 Utilized Clusters (% Memory usage)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(5, (1 - sum(:node_memory_MemAvailable_bytes:sum{clusterType=\"ocp3\"}) by (cluster) / sum(kube_node_status_allocatable_memory_bytes{clusterType=\"ocp3\"}) by (cluster)))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Bandwidth Utilization",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(instance:node_network_receive_bytes_excluding_lo:rate1m{clusterType=\"ocp3\",job=\"node-exporter\"}) by (cluster)"
    },
    {
     "expr": "sum(instance:node_network_transmit_bytes_excluding_lo:rate1m{clusterType=\"ocp3\",job=\"node-exporter\"}) by (cluster)"
    },
    {
     "expr": "sum(instance:node_network_receive_drop_excluding_lo:rate1m{clusterType=\"ocp3\",job=\"node-exporter\"}) by (cluster)"
    },
    {
     "expr": "sum(instance:node_network_transmit_drop_excluding_lo:rate1m{clusterType=\"ocp3\",job=\"node-exporter\"}) by (cluster)"
    }
   ]
  }
 ]
}