{
 "title": "Executive dashboards / Clusters Overview",
 "description": "This dashboard provides insights for the health of the OpenShift Virtualization operator and displays key metrics for virtual machines at the cluster level across multiple clusters. It helps monitor and assess the status of virtualization resources, ensuring ease of operation and quick identification of issues.",
 "tags": [
  "OpenShift",
  "Virtualization",
  "ACM",
  "KubeVirt"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kubevirt_hyperconverged_operator_health_status, cluster)"
    }
   },
   {
    "name": "operator_health",
    "label": "Operator Health",
    "query": "Healthy : ==0, Warning : ==1, Critical : ==2"
   }
  ]
 },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Clusters",
   "type": "stat",
   "description": "Total clusters with OpenShift Virtualization.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (\nlabel_replace(sum by (name, openshiftVersion) (acm_managed_cluster_labels{name=~\"$cluster\"}), \"cluster\", \"$1\", \"name\", \"(.*)\") + \non(cluster) group_left()(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"}*0)\n)"
    }
   ]
  },
  {
   "title": "Clusters in Critical Health",
   "type": "stat",
   "description": "Total number of clusters with critical issues that impact the operator health, which are based on alerts and the operator conditions. This means there is a risk of core functionality loss for your clusters.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"} == 2) or vector(0)"
    }
   ]
  },
  {
   "title": "Total Allocatable Nodes",
   "type": "stat",
   "description": "Total number of nodes that are available to host virtual machines.",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (cluster) (count(kube_node_status_allocatable{resource=~\".*kubevirt.*\", cluster!~\"local-cluster\"}) by (cluster,node)))"
    }
   ]
  },
  {
   "title": "Total VMs",
   "type": "stat",
   "description": "Total number of virtual machines.",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}) by (name))"
    }
   ]
  },
  {
   "title": "Virtual Machines by Status",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}>0) by (name)) or vector(0)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(count(kubevirt_vm_non_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}>0) by (name)) or vector(0)",
     "legendFormat": "Stopped"
    },
    {
     "expr": "sum(count(kubevirt_vm_error_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}>0) by (name)) or vector(0)",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(count(kubevirt_vm_starting_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}>0) by (name)) or vector(0)",
     "legendFormat": "Starting"
    },
    {
     "expr": "sum(count(kubevirt_vm_migrating_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}>0) by (name)) or vector(0)",
     "legendFormat": "Migrating"
    }
   ]
  },
  {
   "title": "Clusters in Warning Health",
   "type": "stat",
   "description": "Total number of clusters with warning level issues that impact the operator health, which are based on alerts and the operator conditions. This means there is a risk of core functionality loss for your clusters.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"} == 1) or vector(0)"
    }
   ]
  },
  {
   "title": "Number of VMs started in the last 7 days",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (cluster)(time() - (label_replace(kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}>0 ,\"status\",\"starting\",\"\",\"\")) < 604800)"
    }
   ]
  },
  {
   "title": "Clusters by Operator Version",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "count by (version)(count by (cluster, version) (csv_succeeded{name=~\".*hyperconverged.*\",cluster=~\"$cluster\"}>0)) or (count by (version,phase, reason)(count by (cluster, version,phase, reason) (csv_abnormal{name=~\".*hyperconverged.*\",cluster=~\"$cluster\"}>0)))",
     "legendFormat": "{{version}}"
    },
    {
     "expr": "count by (version)(\n    count by (cluster, version) (csv_succeeded{name=~\".*hyperconverged.*\",cluster=~\"$cluster\"})\n)/\n(count by (version) (csv_succeeded{name=~\".*hyperconverged.*\"}))"
    }
   ]
  },
  {
   "title": "Clusters by OpenShift Version",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 7 },
   "targets": [
    {
     "expr": "count by (openshiftVersion)(\nlabel_replace(sum by (name, openshiftVersion) (acm_managed_cluster_labels{name=~\"$cluster\"}), \"cluster\", \"$1\", \"name\", \"(.*)\") + \non(cluster) group_left()(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"}*0)\n)",
     "legendFormat": "{{openshiftVersion}}"
    },
    {
     "expr": "count by (openshiftVersion)(count by (cluster, openshiftVersion)(\nlabel_replace(sum by (name, openshiftVersion) (acm_managed_cluster_labels{name=~\"$cluster\"}), \"cluster\", \"$1\", \"name\", \"(.*)\") + \non(cluster) group_left()(kubevirt_hyperconverged_operator_health_status*0)\n)) \n/ (count by (openshiftVersion)(\nlabel_replace(sum by (name, openshiftVersion) (acm_managed_cluster_labels{name=~\"$cluster\"}), \"cluster\", \"$1\", \"name\", \"(.*)\") + \non(cluster) group_left()(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"}*0)\n))"
    }
   ]
  },
  { "title": "Operator Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Operator Health by Cluster",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "(sum(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"}$operator_health) by (cluster))"
    },
    {
     "expr": "(sum(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"}$operator_health) by (cluster))*0 + on (cluster) group_left() (sum by (cluster)(ALERTS{kubernetes_operator_part_of=\"kubevirt\", alertstate=\"firing\",cluster=~\"$cluster\",operator_health_impact=\"critical\"}) or \n (sum by (cluster)(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"}*0)))"
    },
    {
     "expr": "(sum(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"}$operator_health) by (cluster))*0 + on (cluster) group_left() (sum by (cluster)(ALERTS{kubernetes_operator_part_of=\"kubevirt\", alertstate=\"firing\",cluster=~\"$cluster\",operator_health_impact=\"warning\"}) or (sum by (cluster)(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"}*0)))"
    },
    {
     "expr": "(sum(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"}$operator_health) by (cluster))*0 + on (cluster) group_left() (sum by (cluster)(cnv:vmi_status_running:count{cluster=~\"$cluster\"})) or ((sum(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"}$operator_health) by (cluster))*0)"
    },
    {
     "expr": "sum(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"}$operator_health) by (cluster) * 0 \n+ on (cluster) group_left(openshiftVersion) (\n  label_replace(sum by (name, openshiftVersion) (acm_managed_cluster_labels), \"cluster\", \"$1\", \"name\", \"(.*)\")\n )"
    },
    {
     "expr": "sum by (cluster)(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"} $operator_health)*0 \n+ on(cluster) (kubevirt_hco_system_health_status{cluster=~\"$cluster\"} )"
    }
   ]
  },
  {
   "title": "Additional Virtual Machines Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running VMs by OS",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (os)(sum by (cluster, os)(label_replace(kubevirt_vmi_info{cluster=~\"$cluster\", guest_os_name!=\"\", phase=\"running\"}, \"os\", \"$1\", \"guest_os_name\", \"(.*)\")) or\non(cluster) sum(kubevirt_vmi_phase_count{cluster=~\"$cluster\", phase=~\"running\", os!=\"<none>\"}) by (cluster, os))"
      },
      {
       "expr": "sum by (os)(sum by (cluster, os)(label_replace(kubevirt_vmi_info{cluster=~\"$cluster\", guest_os_name=\"\", phase=\"running\", os=\"<none>\"}, \"os\", \"unknown\", \"guest_os_name\", \"\")) or\non(cluster) sum(label_replace(kubevirt_vmi_phase_count{cluster=~\"$cluster\", phase=~\"running\", os=\"<none>\"}, \"os\", \"unknown\", \"os\", \"<none>\")) by (cluster, os))"
      }
     ]
    },
    {
     "title": "Running VMs by Cluster - Top 20",
     "type": "timeseries",
     "description": "Top 20 Clusters",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(20, count by (cluster) (kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0))",
       "legendFormat": "{{cluster}} "
      }
     ]
    },
    {
     "title": "Virtual Machines by Status",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(count(kubevirt_vm_starting_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0)) or vector(0)",
       "legendFormat": "starting"
      },
      {
       "expr": "sum(count(kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0)) or vector(0)",
       "legendFormat": "running"
      },
      {
       "expr": "sum(count(kubevirt_vm_migrating_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0)) or vector(0)",
       "legendFormat": "migrating"
      },
      {
       "expr": "sum(count(kubevirt_vm_error_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0)) or vector(0)",
       "legendFormat": "error"
      },
      {
       "expr": "sum(count(kubevirt_vm_non_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0)) or vector(0)",
       "legendFormat": "stopped"
      }
     ]
    },
    {
     "title": "Running VMs by Node - Top 20",
     "type": "timeseries",
     "description": "Top 20 Nodes",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(20, sum(kubevirt_vmi_phase_count{cluster=~\"$cluster\",namespace=~\".*\", phase=~\"running\"}) by (cluster,phase,node))",
       "legendFormat": "{{cluster}} | {{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources Utilization - Top 20",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage by Cluster",
     "type": "timeseries",
     "description": "Top 20 Clusters",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(20, sum(rate(kubevirt_vmi_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\"}[1h])) by (cluster))",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Memory Usage by Cluster",
     "type": "timeseries",
     "description": "Top 20 Clusters",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(20, sum by (cluster)(kubevirt_vmi_memory_available_bytes{cluster=~\"$cluster\"} - kubevirt_vmi_memory_unused_bytes{cluster=~\"$cluster\"} -kubevirt_vmi_memory_cached_bytes{cluster=~\"$cluster\"}))",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Network Usage by Cluster - Recieve",
     "type": "timeseries",
     "description": "Top 20 Clusters",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(20,sum(rate(kubevirt_vmi_network_receive_bytes_total{cluster=~\"$cluster\"}[1h])) by (cluster))",
       "legendFormat": "{{cluster}} - Receive"
      }
     ]
    },
    {
     "title": "Network Usage by Cluster - Transmit",
     "type": "timeseries",
     "description": "Top 20 Clusters",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(20,sum(rate(kubevirt_vmi_network_transmit_bytes_total{cluster=~\"$cluster\"}[1h])) by (cluster))",
       "legendFormat": "{{cluster}} - Transmit"
      }
     ]
    },
    {
     "title": "Storage IOPs by Cluster",
     "type": "timeseries",
     "description": "Top 20 Clusters",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "topk(20, sum by (cluster) (rate(kubevirt_vmi_storage_iops_read_total{cluster=~\"$cluster\"}[1h]) + rate(kubevirt_vmi_storage_iops_write_total{cluster=~\"$cluster\"}[1h])))",
       "legendFormat": "{{cluster}}"
      }
     ]
    }
   ]
  }
 ]
}