{
 "title": "Executive dashboards / Single Virtual Machine View",
 "description": "This dashboard provides detailed insights into a specific virtual machine, including its configuration, resource consumption, and any active alerts. It allows users to easily locate the virtual machine across multiple clusters, facilitating efficient monitoring and troubleshooting.",
 "tags": [
  "ACM",
  "KubeVirt",
  "OpenShift",
  "Virtualization"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "VM Name",
    "query": {
     "query": "label_values(kubevirt_vm_running_status_last_transition_timestamp_seconds, name)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kubevirt_vm_running_status_last_transition_timestamp_seconds{name=\"$name\"}, namespace)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kubevirt_vm_running_status_last_transition_timestamp_seconds{name=\"$name\", namespace=\"$namespace\"}, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=\"$cluster\",namespace=\"$namespace\",name=\"$name\"}>0) by (name))",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(count(kubevirt_vm_non_running_status_last_transition_timestamp_seconds{cluster=\"$cluster\",namespace=\"$namespace\",name=\"$name\"}>0) by (name))",
     "legendFormat": "Stopped"
    },
    {
     "expr": "sum(count(kubevirt_vm_error_status_last_transition_timestamp_seconds{cluster=\"$cluster\",namespace=\"$namespace\",name=\"$name\"}>0) by (name))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(count(kubevirt_vm_starting_status_last_transition_timestamp_seconds{cluster=\"$cluster\",namespace=\"$namespace\",name=\"$name\"}>0) by (name))",
     "legendFormat": "Starting"
    },
    {
     "expr": "sum(count(kubevirt_vm_migrating_status_last_transition_timestamp_seconds{cluster=\"$cluster\",namespace=\"$namespace\",name=\"$name\"}>0) by (name))",
     "legendFormat": "Migrating"
    }
   ]
  },
  {
   "title": "VM Details",
   "type": "table",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, name)(kubevirt_vmi_network_receive_bytes_total{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\"})"
    },
    {
     "expr": "(sum by (cluster, namespace, name)(kubevirt_vm_starting_status_last_transition_timestamp_seconds{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\"}>0) or\nsum by (cluster, namespace, name)(kubevirt_vm_non_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\"}>0 or \nsum by (cluster, namespace, name)(kubevirt_vm_error_status_last_transition_timestamp_seconds{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\"}>0) or \nsum by (cluster, namespace, name)(kubevirt_vm_migrating_status_last_transition_timestamp_seconds{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\"}>0) or \nsum by (cluster, namespace, name)(kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\"}>0)))*1000"
    }
   ]
  },
  {
   "title": "Allocated Resources",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (name)(kubevirt_vm_resource_requests{cluster=\"$cluster\",namespace=\"$namespace\", name=\"$name\",resource=\"memory\"})"
    },
    {
     "expr": "sum by (name)((kubevirt_vm_resource_requests{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\", resource=\"cpu\", unit=\"cores\"} *\non (cluster, namespace, vmi) group_left() kubevirt_vm_resource_requests{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\", resource=\"cpu\", unit=\"sockets\"}*\n on (cluster, namespace, vmi) group_left() kubevirt_vm_resource_requests{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\", resource=\"cpu\", unit=\"threads\"}))"
    }
   ]
  },
  {
   "title": "Template Details",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "targets": [
    {
     "expr": "sum by(name, preference, workload, flavor, instance_type, guest_os_name, guest_os_version_id )(kubevirt_vmi_info{cluster=\"$cluster\", namespace=\"$namespace\", name=\"$name\"})"
    }
   ]
  },
  {
   "title": "Instance Type Details",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by(name, preference, workload, flavor, instance_type, guest_os_name, guest_os_version_id )(kubevirt_vmi_info{cluster=\"$cluster\", namespace=\"$namespace\", name=\"$name\"})"
    }
   ]
  },
  {
   "title": "Operating System Details",
   "type": "table",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "expr": "sum by(name, preference, workload, flavor, instance_type, guest_os_name, guest_os_version_id )(kubevirt_vmi_info{cluster=\"$cluster\", namespace=\"$namespace\", name=\"$name\"})"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (name) (rate(kubevirt_vmi_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=\"$namespace\", name=\"$name\"}[1h]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (name) (\nkubevirt_vmi_memory_available_bytes{cluster=~\"$cluster\",namespace=\"$namespace\", name=\"$name\"} - kubevirt_vmi_memory_unused_bytes{cluster=~\"$cluster\",namespace=\"$namespace\", name=\"$name\"} -kubevirt_vmi_memory_cached_bytes{cluster=~\"$cluster\",namespace=\"$namespace\", name=\"$name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Network Usage  - Transmit",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(kubevirt_vmi_network_transmit_bytes_total{cluster=~\"$cluster\",namespace=\"$namespace\", name=\"$name\"}[1h])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Network Usage - Receive",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(kubevirt_vmi_network_receive_bytes_total{cluster=~\"$cluster\",namespace=\"$namespace\", name=\"$name\"}[1h])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Storage IOPs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by (name) (rate(kubevirt_vmi_storage_iops_read_total{cluster=~\"$cluster\",namespace=\"$namespace\", name=\"$name\"}[1h]) + rate(kubevirt_vmi_storage_iops_write_total{cluster=~\"$cluster\",namespace=\"$namespace\", name=\"$name\"}[1h]))",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Critical Severity Alerts",
     "type": "stat",
     "description": "Total number of alerts that are firing with the severity level: critical.",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum by (cluster,alertname,alertstate,severity,namespace,name,operator_health_impact )(ALERTS{cluster=~\"$cluster\",kubernetes_operator_part_of=\"kubevirt\", alertstate=\"firing\", pod=~\"virt-launcher-$name.*\", severity=\"critical\"})) or vector(0)"
      }
     ]
    },
    {
     "title": "Warning Severity Alerts",
     "type": "stat",
     "description": "Total number of alerts that are firing with the severity level: warning.",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum by (cluster,alertname,alertstate,severity,namespace,name,operator_health_impact )(ALERTS{cluster=~\"$cluster\",kubernetes_operator_part_of=\"kubevirt\", alertstate=\"firing\", pod=~\"virt-launcher-$name.*\", severity=\"warning\"}))  or vector(0)"
      }
     ]
    },
    {
     "title": "Info Severity Alerts",
     "type": "stat",
     "description": "Total number of alerts that are firing with the severity level: warning.",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum by (cluster,alertname,alertstate,severity,namespace,name,operator_health_impact )(ALERTS{cluster=~\"$cluster\",kubernetes_operator_part_of=\"kubevirt\", alertstate=\"firing\", pod=~\"virt-launcher-$name.*\", severity=\"info\"})) or vector(0)"
      }
     ]
    },
    {
     "title": "Operator Alerts",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum by (cluster,alertname,alertstate,severity,namespace,name,operator_health_impact )(ALERTS{cluster=~\"$cluster\",kubernetes_operator_part_of=\"kubevirt\", alertstate=\"firing\", pod=~\"virt-launcher-$name.*\"})"
      }
     ]
    }
   ]
  }
 ]
}