{
 "title": "Kubernetes / Capacity Management - OCP 3.11",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_pod_info{clusterType=\"ocp3\"},cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$cluster Cluster Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quota / Allocatable in Cluster: $cluster",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (openshift_clusterresourcequota_labels{cluster=\"$cluster\"} * on (name) group_right () openshift_clusterresourcequota_usage{resource=\"requests.memory\",type=\"hard\"}) by (cluster))/(sum (kube_node_labels{cluster=\"$cluster\"} * on (node) group_right () kube_node_status_allocatable_memory_bytes) by (cluster))"
    }
   ]
  },
  {
   "title": "Pod requests / Allocatable in Cluster: $cluster",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (kube_node_labels{cluster=\"$cluster\"} * on (node) group_left () sum (kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\"}) by (node)) by (cluster))/(sum (kube_node_labels{cluster=\"$cluster\"} * on (node) group_left () kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"}) by (cluster))"
    }
   ]
  },
  {
   "title": "Current Memory Usage / Allocatable in Cluster: $cluster",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_labels{cluster=\"$cluster\"} * on (node) group_left () sum(kube_pod_info * on (pod) group_left() label_replace(sum(container_memory_usage_bytes{container_name=~\".+\", container_name!=\"POD\"}) by (pod_name),\"pod\",\"$1\",\"pod_name\", \"(.+)\")) by (node)) by (cluster)/(sum (kube_node_labels{cluster=\"$cluster\"} * on (node) group_left () kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"}) by (cluster))"
    }
   ]
  },
  {
   "title": "Sum of Quotas",
   "type": "stat",
   "description": "What has been promised",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (openshift_clusterresourcequota_labels{cluster=\"$cluster\"} * on (name) group_right () openshift_clusterresourcequota_usage{cluster=\"$cluster\",resource=\"requests.memory\",type=\"hard\"}) by (cluster))"
    }
   ]
  },
  {
   "title": "Sum of Pod Requests",
   "type": "stat",
   "description": "What developers estimate they will need",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (kube_node_labels{cluster=\"$cluster\"} * on (node) group_left () sum (kube_pod_container_resource_requests_memory_bytes) by (node)) by (cluster))"
    }
   ]
  },
  {
   "title": "Current Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_labels{cluster=\"$cluster\"} * on (node) group_left () sum(kube_pod_info * on (pod) group_left() label_replace(sum(container_memory_usage_bytes{container_name=~\".+\", container_name!=\"POD\"}) by (pod_name),\"pod\",\"$1\",\"pod_name\", \"(.+)\")) by (node)) by (cluster)"
    }
   ]
  },
  { "title": "$cluster Cluster CPU Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Quota/ Allocatable in Cluster: $cluster",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (openshift_clusterresourcequota_labels{cluster=\"$cluster\"} * on (name) group_right () openshift_clusterresourcequota_usage{resource=\"requests.cpu\",type=\"hard\"}) by (cluster))/(sum (kube_node_labels{cluster=\"$cluster\"} * on (node) group_right () kube_node_status_allocatable_cpu_cores) by (cluster))"
    }
   ]
  },
  {
   "title": "Pod requests / Allocatable in Cluster: $cluster",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (kube_node_labels{cluster=\"$cluster\"} * on (node) group_left () sum (kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\"}) by (node)) by (cluster))/(sum (kube_node_labels{cluster=\"$cluster\"} * on (node) group_left () kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\"}) by (cluster))"
    }
   ]
  },
  {
   "title": "Current CPU Usage in Cluster: $cluster",
   "type": "gauge",
   "description": "OS and Container CPU usage",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_labels{cluster=\"$cluster\"} * on (node) group_left () sum(kube_pod_info * on (pod) group_left() label_replace(sum(rate (container_cpu_usage_seconds_total{container_name=~\".+\", container_name!=\"POD\"} [$__rate_interval])) by (pod_name),\"pod\",\"$1\",\"pod_name\", \"(.+)\")) by (node)) by (cluster) / (sum (kube_node_labels{cluster=\"$cluster\"} * on (node) group_left () kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\"}) by (cluster)) / (sum (kube_node_labels{cluster=\"$cluster\"} * on (node) group_left () kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\"}) by (cluster))"
    }
   ]
  },
  {
   "title": "Sum of Quotas",
   "type": "stat",
   "description": "What has been promised",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (openshift_clusterresourcequota_labels{cluster=\"$cluster\"} * on (name) group_right () openshift_clusterresourcequota_usage{cluster=\"$cluster\",resource=\"requests.cpu\",type=\"hard\"}) by (cluster))"
    }
   ]
  },
  {
   "title": "Sum of Pod Requests",
   "type": "stat",
   "description": "What developers estimate they will need",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (kube_node_labels{cluster=\"$cluster\"} * on (node) group_left () sum (kube_pod_container_resource_requests_cpu_cores) by (node)) by (cluster))"
    }
   ]
  },
  {
   "title": "Current CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_labels{cluster=\"$cluster\"} * on (node) group_left () sum(kube_pod_info * on (pod) group_left() label_replace(sum(rate (container_cpu_usage_seconds_total{container_name=~\".+\", container_name!=\"POD\"} [$__rate_interval])) by (pod_name),\"pod\",\"$1\",\"pod_name\", \"(.+)\")) by (node)) by (cluster) / (sum (kube_node_labels{cluster=\"$cluster\"} * on (node) group_left () kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\"}) by (cluster))"
    }
   ]
  }
 ]
}