{
 "title": "ACM - Hosted Control Planes Overview",
 "tags": [ "ACM" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "num_hcps",
    "query": {
     "query": "mce_hs_addon_total_hosted_control_planes_gaug"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Estimated capacity based on HCP resource requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": " Resource Request-base Limit Estimation",
   "type": "text",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "## Request-based resource limit\n\nTo understand the request-based resource limit, consider the total request value of a hosted control plane. To calculate that value, add the request values of all highly available hosted control plane pods across the namespace. The estimates are calculated based on the following resource request samples:\n\n* 78 pods\n* Five vCPU requests for each highly available hosted control plane\n* 18 GiB memory requests for each highly available hosted control plane"
   }
  },
  {
   "title": "Worker Nodes Capacities",
   "type": "table",
   "description": "These are the worker nodes that can run hosted control planes.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "mce_hs_addon_worker_node_resource_capacities_gauge"
    }
   ]
  },
  {
   "title": "Number of HCPs",
   "type": "bargauge",
   "description": "This panel displays the current number of unavailable/failing and available hosted control planes. Based on the hosted control plane resource requirements, it also displays the estimated maximum number of hosted control planes that can be hosted in this cluster.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mce_hs_addon_hosted_control_planes_status_gauge{ready=\"false\"})",
     "legendFormat": "Currently Unavailable"
    },
    {
     "expr": "sum(mce_hs_addon_hosted_control_planes_status_gauge{ready=\"true\"})",
     "legendFormat": "Currently Available"
    },
    {
     "expr": "mce_hs_addon_request_based_hcp_capacity_gauge",
     "legendFormat": "est. Max"
    }
   ]
  },
  {
   "title": "Estimated capacity based on API server query (QPS)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "Load-based Limit Estimation",
   "type": "text",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 14 },
   "options": {
    "content": "## Load-based limit\n\nRequest-based sizing provides a maximum number of hosted control planes that can run based on the minimum request totals for the `Burstable` class, which meet the average resource usage. For sizing guidance that is tuned to higher levels of hosted cluster load, the load-based approach demonstrates resource usage at increasing API rates. The load-based approach builds in resource capacity for each hosted control plane to handle higher API load points.\n\nResource utilization is measured as the workload increased to the total namespace count. This data provides an estimation factor to increase the compute resource capacity based on the expected API load. Exact utilization rates can vary based on the type and pace of the cluster workload. \n\n| **Hosted control plane resource utilization scaling** | **vCPUs** | **Memory (GiB)** |\n| --- | --- | --- |\n| Default requests | 5 | 18 |\n| Usage when idle | 2.9 | 11.1 |\n| Incremental usage per 1000 increase in API rate | 9.0 | 2.5 |\n\nBy using these examples, you can factor in a load-based limit that is based on the expected rate of stress on the API, which is measured as the aggregated QPS across the 3 hosted API servers. For general sizing purposes, consider a 1000 QPS API rate to be a medium hosted cluster load and a 2000 QPS API to be a heavy hosted cluster load."
   }
  },
  {
   "title": "QPS Settings",
   "type": "table",
   "description": "These API server loads are used for estimating the maximum number of hosted control planes that can be hosted. For example, the est. Max. (low QPS) in the panel below is the estimate maximum number of hosted control planes that can be hosted when all hosted control planes put low load on the API server.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "targets": [
    { "expr": "mce_hs_addon_qps_gauge" }
   ]
  },
  {
   "title": "Number of HCPs ",
   "type": "bargauge",
   "description": "This panel displays the current number of unavailable/failing and available hosted control planes. Based on various loads, it also displays the estimated maximum number of hosted control planes that can be hosted in this cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mce_hs_addon_hosted_control_planes_status_gauge{ready=\"false\"})",
     "legendFormat": "Currently Unavailable"
    },
    {
     "expr": "sum(mce_hs_addon_hosted_control_planes_status_gauge{ready=\"true\"})",
     "legendFormat": "Currently Available"
    },
    {
     "expr": "mce_hs_addon_qps_based_hcp_capacity_gauge{qps_rate=\"low\"}",
     "legendFormat": "est. Max. (low QPS)"
    },
    {
     "expr": "mce_hs_addon_qps_based_hcp_capacity_gauge{qps_rate=\"medium\"}",
     "legendFormat": "est. Max. (medium QPS)"
    },
    {
     "expr": "mce_hs_addon_qps_based_hcp_capacity_gauge{qps_rate=\"high\"}",
     "legendFormat": "est. Max. (high QPS)"
    },
    {
     "expr": "mce_hs_addon_qps_based_hcp_capacity_gauge{qps_rate=\"average\"}",
     "legendFormat": "est. Max. (avg QPS)"
    }
   ]
  },
  { "title": "Hosted Control Planes List", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Hosted Control Plane List",
   "type": "table",
   "description": "This is the list of all hosted control planes in this cluster. Click on the hosted control plane name to see its resource utilization.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "mce_hs_addon_hosted_control_planes_status_gauge"
    }
   ]
  }
 ]
}