{
 "title": "Executive dashboards / Single Cluster View",
 "description": "This dashboard provides comprehensive insights into the cluster with OpenShift Virtualization installed. It offers detailed information about the virtual machines (VMs), associated resources, and any active alerts, enabling efficient monitoring and management of virtualization within the cluster.",
 "tags": [
  "Openshift",
  "Virtualization",
  "KubeVirt",
  "ACM"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kubevirt_hyperconverged_operator_health_status{name=~\".*hyperconverged.*\"},cluster)"
    }
   },
   {
    "name": "health_impact",
    "label": "Alerts - Impact on Operator Health",
    "query": {
     "query": "label_values(ALERTS{kubernetes_operator_part_of=\"kubevirt\"}, operator_health_impact)"
    }
   },
   {
    "name": "severity",
    "label": "Alerts - Severity",
    "query": {
     "query": "label_values(ALERTS{kubernetes_operator_part_of=\"kubevirt\"}, severity)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubevirt_hyperconverged_operator_health_status{name=~\".*hyperconverged.*\", cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Openshift Virt Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csv_succeeded{name=~\".*hyperconverged.*\", cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "stat",
   "description": "Total node count in OpenShift Virtualization clusters",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (cluster) (count(kube_node_status_allocatable{resource=~\".*kubevirt.*\", cluster=~\"$cluster\"}) by (cluster,node)))"
    }
   ]
  },
  {
   "title": "Total VMs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(kubevirt_vm_error_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}) by (name))"
    }
   ]
  },
  {
   "title": "Virtual Machines by Status",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}>0) by (name)) or vector(0)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(count(kubevirt_vm_non_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}>0) by (name)) or vector(0)",
     "legendFormat": "Stopped"
    },
    {
     "expr": "sum(count(kubevirt_vm_error_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}>0) by (name)) or vector(0)",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(count(kubevirt_vm_starting_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}>0) by (name)) or vector(0)",
     "legendFormat": "Starting"
    },
    {
     "expr": "sum(count(kubevirt_vm_migrating_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}>0) by (name)) or vector(0)",
     "legendFormat": "Migrating"
    }
   ]
  },
  {
   "title": "Provider",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(acm_managed_cluster_labels{name=~\"$cluster\"}) by (cloud)"
    }
   ]
  },
  {
   "title": "Openshift Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(acm_managed_cluster_labels{name=~\"$cluster\"}) by (openshiftVersion)"
    }
   ]
  },
  {
   "title": "Operator Status",
   "type": "stat",
   "description": "Inspect the Operator Conditions and the Alerts tab for additional details",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster)(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Operator Conditions",
   "type": "stat",
   "description": "Status of HCO conditions - Check the HCO Conditions in the cluster",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (kubevirt_hco_system_health_status{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Running VMs by OS",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (os)(sum by (cluster, os)(label_replace(kubevirt_vmi_info{cluster=~\"$cluster\", guest_os_name!=\"\", phase=\"running\"}, \"os\", \"$1\", \"guest_os_name\", \"(.*)\")) or\non(cluster) sum(kubevirt_vmi_phase_count{cluster=~\"$cluster\", phase=~\"running\", os!=\"<none>\"}) by (cluster, os))"
    },
    {
     "expr": "sum by (os)(sum by (cluster, os)(label_replace(kubevirt_vmi_info{cluster=~\"$cluster\", guest_os_name=\"\", phase=\"running\", os=\"<none>\"}, \"os\", \"unknown\", \"guest_os_name\", \"\")) or\non(cluster) sum(label_replace(kubevirt_vmi_phase_count{cluster=~\"$cluster\", phase=~\"running\", os=\"<none>\"}, \"os\", \"unknown\", \"os\", \"<none>\")) by (cluster, os))"
    }
   ]
  },
  {
   "title": "Recent VMs started",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "bottomk(5, sum by (name, namespace) (sort(time() - kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}) / 1 ))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Additional Virtual Machines Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "VMs Running by Node",
     "type": "timeseries",
     "description": "Top 20 nodes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(20, sum(kubevirt_vmi_phase_count{cluster=~\"$cluster\",namespace=~\".*\", phase=~\"running\"}) by (cluster,phase,node))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "VMs by Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(count(kubevirt_vm_starting_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0)) or vector(0)",
       "legendFormat": "starting"
      },
      {
       "expr": "sum(count(kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0)) or vector(0)",
       "legendFormat": "running"
      },
      {
       "expr": "sum(count(kubevirt_vm_migrating_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0)) or vector(0)",
       "legendFormat": "migrating"
      },
      {
       "expr": "sum(count(kubevirt_vm_error_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0)) or vector(0)",
       "legendFormat": "error"
      },
      {
       "expr": "sum(count(kubevirt_vm_non_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0)) or vector(0)",
       "legendFormat": "stopped"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources Utilization - Top 20",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage by Nodes",
     "type": "timeseries",
     "description": "Top 20 nodes",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(20,sum(label_replace(instance:node_cpu_utilisation:rate1m{cluster=~\"$cluster\"}, \"node\", \"$1\", \"instance\", \"(.*)\")) by (node, cluster)\n+ on(node, cluster) group_left()\n0*sum(kubevirt_vmi_cpu_usage_seconds_total{cluster=~\"$cluster\"}) by (node, cluster))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "CPU Usage by VM",
     "type": "timeseries",
     "description": "Top 20 VMs",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(20,sum by (name) (rate(kubevirt_vmi_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\"}[1h])))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory Usage by Nodes",
     "type": "timeseries",
     "description": "Top 20 nodes with virtualization workloads",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(20,sum(label_replace(instance:node_memory_utilisation:ratio{cluster=~\"$cluster\"}, \"node\", \"$1\", \"instance\", \"(.*)\")) by (node, cluster)\n+ on(node, cluster) group_left()\n0*sum(kubevirt_vmi_memory_used_bytes{cluster=~\"$cluster\"}) by (node, cluster))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Memory Usage by VM",
     "type": "timeseries",
     "description": "Top 20 VMs ",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(20,sum by (name) (\nkubevirt_vmi_memory_available_bytes{cluster=~\"$cluster\",namespace=~\".*\"} - kubevirt_vmi_memory_unused_bytes{cluster=~\"$cluster\",namespace=~\".*\"} -kubevirt_vmi_memory_cached_bytes{cluster=~\"$cluster\",namespace=~\".*\"}))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Network Usage by Nodes - Receive",
     "type": "timeseries",
     "description": "Top 20 nodes",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(20,sum(label_replace(rate(instance:node_network_receive_bytes_excluding_lo:rate1m{cluster=\"$cluster\"}[1h]), \"node\", \"$1\", \"instance\", \"(.*)\")) by (node, cluster)\n+ on(node, cluster) group_left()\n0*sum(kubevirt_vmi_network_receive_packets_total{cluster=\"$cluster\"}) by (node, cluster))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Network Usage by VM - Receive",
     "type": "timeseries",
     "description": "Top 20 VMs",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(20,sum(rate(kubevirt_vmi_network_receive_bytes_total{cluster=~\"$cluster\"}[1h])) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Network Usage by Nodes - Transmit",
     "type": "timeseries",
     "description": "Top 20 nodes",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(20,sum(label_replace(instance:node_network_transmit_bytes_excluding_lo:rate1m{cluster=\"$cluster\"}, \"node\", \"$1\", \"instance\", \"(.*)\")) by (node, cluster)\n+ on(node, cluster) group_left()\n0*sum(kubevirt_vmi_network_transmit_packets_total{cluster=\"$cluster\"}) by (node, cluster))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Network Usage by VM  - Transmit",
     "type": "timeseries",
     "description": "Top 20 VMs",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(20,sum(rate(kubevirt_vmi_network_transmit_bytes_total{cluster=~\"$cluster\"}[1h])) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Storage IOPs by Node",
     "type": "timeseries",
     "description": "Top 20 nodes",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "topk(20,sum by (node) (rate(kubevirt_vmi_storage_iops_read_total{cluster=~\"$cluster\"}[1h]) + rate(kubevirt_vmi_storage_iops_write_total{cluster=~\"$cluster\"}[1h])))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Storage IOPs by VM",
     "type": "timeseries",
     "description": "Top 20 VMs",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "topk(20,sum by (name) (rate(kubevirt_vmi_storage_iops_read_total{cluster=~\"$cluster\"}[1h]) + rate(kubevirt_vmi_storage_iops_write_total{cluster=~\"$cluster\"}[1h])))",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Critical Severity Alerts",
     "type": "stat",
     "description": "Total number of alerts that are firing with the severity level: critical.",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (ALERTS{kubernetes_operator_part_of=\"kubevirt\", alertstate=\"firing\",cluster=~\"$cluster\",severity=\"critical\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Warning Severity Alerts",
     "type": "stat",
     "description": "Total number of alerts that are firing with the severity level: warning.",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (ALERTS{kubernetes_operator_part_of=\"kubevirt\", alertstate=\"firing\",cluster=~\"$cluster\",severity=\"warning\",operator_health_impact=~\"$health_impact\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Info Severity Alerts",
     "type": "stat",
     "description": "Total number of alerts that are firing with the severity level: warning.",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (ALERTS{kubernetes_operator_part_of=\"kubevirt\", alertstate=\"firing\",cluster=~\"$cluster\",severity=\"info\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Operator Health Impact Alerts",
     "type": "table",
     "gridPos": { "h": 5, "w": 16, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum(ALERTS{cluster=~\"$cluster\",alertstate=\"firing\",kubernetes_operator_part_of=\"kubevirt\",operator_health_impact=~\"$health_impact\",operator_health_impact!=\"none\", severity=~\"$severity\"}) by (cluster,alertname,alertstate,severity,namespace,name,operator_health_impact)"
      }
     ]
    },
    {
     "title": "Operator CSV Issues",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
     "targets": [
      {
       "expr": "count by (version,phase, reason) (csv_abnormal{name=~\".*hyperconverged.*\",cluster=~\"$cluster\"}>0)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "All Alerts",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum(ALERTS{cluster=~\"$cluster\",alertstate=\"firing\",kubernetes_operator_part_of=\"kubevirt\",operator_health_impact=~\"$health_impact\", severity=~\"$severity\"}) by (cluster,alertname,alertstate,severity,namespace,name,operator_health_impact)"
      }
     ]
    }
   ]
  }
 ]
}