apiVersion: v1
data:
  config.yaml: |
    server:
      grpcListenAddr: ":3593"
      requestLimits:
        maxActionsPerResource: 5
        maxResourcesPerRequest: 500
      advanced:
        grpc:
          maxRecvMsgSizeBytes: 8388608
      logRequestPayloads: false

    engine:
      defaultPolicyVersion: "default"

    storage:
      driver: "git"
      git:
        protocol: https
        url: https://github.com/michaelalang/prom-policies.git
        branch: main
        subDir: policies
        checkoutDir: /policies
        updatePollInterval: 10s
        operationTimeout: 30s
        https:
          username: ${GITHUB_USERNAME}
          password: ${GITHUB_TOKEN}

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: cerbosconfig
