apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cerbosconfig.yml
- deploy-perses.yml
- deploy.yml
- monitoring-stack.yml
- namespace.yml
- podmonitor.yml
- policycreds-secret.yml
- route.yml
- service-perses.yml
- service.yml
- thanos-querier.yml

images:
- name: localhost/prom-authz
  newName: ghcr.io/michaelalang/prom-authz
  newTag: v1.0.4
