apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cerbosconfig.yml
- deploy-perses.yml
- deploy.yml
#- monitoring-stack.yml
- namespace.yml
- podmonitor.yml
- policycreds-secret.yml
- route.yml
- service-perses.yml
- service.yml
#- thanos-querier.yml
- collector-cm.yml
- deploy-1.yml

images:
- name: localhost/prom-authz
  newName: quay.chester.at/infrastructure/prom-authz
  newTag: v2.0.0
