apiVersion: monitoring.rhobs/v1alpha1
kind: MonitoringStack
metadata:
  labels:
    coo: monitoringstack
  name: monitoring-stack
spec:
  alertmanagerConfig:
    disabled: true
  logLevel: debug
  prometheusConfig:
    enableOtlpHttpReceiver: true
    replicas: 1
  resourceSelector:
    matchLabels:
      coo: monitoringstack
  resources:
    limits:
      cpu: 2
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 256Mi
  retention: 1d
