apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: policycreds
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: gogs
      metadataPolicy: None
      property: "milang-token"
    secretKey: token
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: "milang"
      metadataPolicy: None
      property: username
    secretKey: username
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: policycreds
    template:
      data:
        username: "{{ .username }}"
        token: "{{ .token }}"
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque

