apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-sqlite
  namespace: open-cluster-management-observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hostpath-csi
  volumeMode: Filesystem
